language: php

php:
  - 8.0

services:
  - rabbitmq-server

addons:
  apt:
    packages:
      - rabbitmq-server

env:
  matrix:
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - composer run-script test-ci

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && chmod +x ocular.phar
  - travis_retry php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar && chmod +x php-coveralls.phar
  - travis_retry php php-coveralls.phar -vvv -x coverage.clover -o ./coverall.json
